### ISSUE TITLE
MPMediaItemPropertyPlaybackDuration

### ISSUE THREAD

**Issue by syrakozz** [0x0c/LMMediaPlayer#14]
can you plz add 
MPMediaItemPropertyPlaybackDuration and MPNowPlayingInfoPropertyPlaybackRate  to updateLockScreenInfo

thanks

**Comment by 0x0c** [comment]
https://github.com/0x0c/LMMediaPlayer/commit/f88b32c356bd01e084e7d50ccec4b6a276cff219
