### ISSUE TITLE
Import "LMMediaPlayer" twice

### ISSUE THREAD

**Issue by zsk425** [0x0c/LMMediaPlayer#17]
c50262ff8e82a2822f29defacf0401aeb9f1e6a9

duplicate symbol _OBJC_METACLASS_$_LMMediaItemStreamingCache in:
    /Users/zhaosk/Library/Developer/Xcode/DerivedData/LMMediaPlayer-dsdiqyvwyauqbidvycmhbqlfdgoz/Build/Intermediates/LMMediaPlayer.build/Debug-iphoneos/LMMediaPlayer.build/Objects-normal/armv7/LMMediaItemStreamingCache.o
    /Users/zhaosk/Library/Developer/Xcode/DerivedData/LMMediaPlayer-dsdiqyvwyauqbidvycmhbqlfdgoz/Build/Products/Debug-iphoneos/libPods-LMMediaPlayer-LMMediaPlayer.a(LMMediaItemStreamingCache.o)
duplicate symbol _OBJC_CLASS_$_LMMediaItemStreamingCache in:
    /Users/zhaosk/Library/Developer/Xcode/DerivedData/LMMediaPlayer-dsdiqyvwyauqbidvycmhbqlfdgoz/Build/Intermediates/LMMediaPlayer.build/Debug-iphoneos/LMMediaPlayer.build/Objects-normal/armv7/LMMediaItemStreamingCache.o
    /Users/zhaosk/Library/Developer/Xcode/DerivedData/LMMediaPlayer-dsdiqyvwyauqbidvycmhbqlfdgoz/Build/Products/Debug-iphoneos/libPods-LMMediaPlayer-LMMediaPlayer.a(LMMediaItemStreamingCache.o)
ld: 2 duplicate symbols for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Reproduce steps:
1.clone the project;
2.cd Example,and pod install;
3.open LMMediaPlayer.xcworkspace/ and then build.

**Comment by 0x0c** [comment]
Thank you for report.
I fix it.
