### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by marinotws** [0x0c/LMMediaPlayer#20]
For short video at 00:00 the Slider indicate still time, see image.

thank you.
![img_6862](https://cloud.githubusercontent.com/assets/8616947/5936460/2534c424-a6e5-11e4-9241-60bf78823c85.PNG)
![img_6861](https://cloud.githubusercontent.com/assets/8616947/5936461/255df38a-a6e5-11e4-8ce4-d5a4234f4707.PNG)

**Comment by 0x0c** [comment]
I'll check it. :smiley:

**Comment by 0x0c** [comment]
Done.
https://github.com/0x0c/LMMediaPlayer/commit/78c0eab7c0949fedf7fe4aafc77fe289d30cfeef
