### ISSUE TITLE
Sometimes not play video on ios7

### ISSUE THREAD

**Issue by hotuy** [0x0c/LMMediaPlayer#21]
Problem with ios7.

When i play video from streaming, log error print:

2015-02-03 18:36:52.257 vietapps[6287:60b] mediaPlayerViewWillChangeState state: 1
2015-02-03 18:37:02.260 vietapps[6287:4b0b] void SendDelegateMessage(NSInvocation *): delegate (webView:decidePolicyForNavigationAction:request:frame:decisionListener:) failed to return after waiting 10 seconds. main run loop mode: kCFRunLoopDefaultMode

Sometimes it's play, sometimes it's not play.
ios8 play good but ios7 sometimes die :(

I'm try to debug but i cannot found the problem.

It's change to state 1 and die.

**Comment by 0x0c** [comment]
Thank you for your report.

**Comment by 0x0c** [comment]
Could you tell me more detail about video like a video format, time interval and streaming method(like http, https)?.
I'll check this issue after your reply :).

**Comment by hotuy** [comment]
Video format: mp3, method: http.
Time interval check where? i using default. Maybe 10 seconds?

Link stream: http://stream9.tv.zdn.vn/streaming/d01e550b83f1e545b1a034a19f0e467f/54d18557/2015/0121/6b/80749e67397eb5062c013ee5583fb61d.mp4?format=f360&device=ios

Here is my code:

- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    
    playerView_.delegate = self;
    playerView_.frame = self.playerView.frame;
    UIView *baseView = [[UIView alloc] initWithFrame:self.playerView.frame];
    baseView.backgroundColor = [UIColor blackColor];
    [baseView addSubview:playerView_];
     baseView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleTopMargin;
    [self.playerView addSubview:baseView];
#if !__has_feature(objc_arc)
    [baseView release];
#endif
}

- (void)playStream
{
    
    [self showLoadingIndicators];
    
    NSLog(@"file_url: %@", [film_detail objectForKey:@"file_url"]);
    NSString *url = [NSString stringWithFormat:@"http://%@", [film_detail objectForKey:@"file_url"]];
    NSURL *path = [NSURL URLWithString:url];
    LMMediaItem *item = [[LMMediaItem alloc] initWithInfo:@{LMMediaItemInfoURLKey:path, LMMediaItemInfoContentTypeKey:@(LMMediaItemContentTypeVideo)}];
    item.title = [[film_detail objectForKey:@"full_name"] stringByReplacingOccurrencesOfString:[NSString stringWithFormat:@"%@ - ", [film_detail objectForKey:@"program_name"]] withString:@""];
    
    [playerView_.mediaPlayer removeAllMediaInQueue];
    
    NSInteger next_media_id = [[film_detail objectForKey:@"next_media_id"] intValue];
    if(next_media_id == 0) playerView_.nextButton.hidden = YES;
    else playerView_.nextButton.hidden = NO;
    //[playerView_.mediaPlayer addMedia:item];
    
    [playerView_.mediaPlayer playMedia:item];
    
}

**Comment by hotuy** [comment]
And next problem, i can auto continue play when network problem, current when poor network it play and stop.

**Comment by 0x0c** [comment]
>And next problem, i can auto continue play when network problem, current when poor network it play several seconds and stop.
The low speed network interfere with download, so playback time overtakes buffer.
It cannot solve with program.

**Comment by hotuy** [comment]
Did you have debug this problem? i don't resolve this problem :(
If using AVPlayer default of iOS is ok, but using this not ok.

**Comment by 0x0c** [comment]
Sorry to late.
I cannot reproduce this problem.
