### ISSUE TITLE
ld: library not found for -lPods-LMMediaPlayer-LMMediaPlayer

### ISSUE THREAD

**Issue by xuncai** [0x0c/LMMediaPlayer#23]
Hi i am very new to cocosPod.
Could anyone tell me how to fix the ld: library not found for -lPods-LMMediaPlayer-LMMediaPlayer problem and 
the following is red:
XCTest.framework,
libPods-Tests.a
libPods-LMMediaPlayer.a

Thanks

**Comment by 0x0c** [comment]
Open .xcodeworkspace file which is generated by cocoapod to build your project.
