### ISSUE TITLE
full screen iOS 8

### ISSUE THREAD

**Issue by marinotws** [0x0c/LMMediaPlayer#24]
in order the capture of problem.

thanks. bye.

![ios simulator screen shot 02 mar 2015 19 26 44](https://cloud.githubusercontent.com/assets/8616947/6447419/79b12ce4-c112-11e4-8f4e-e4eb8d9e63c6.png)

![ios simulator screen shot 02 mar 2015 19 26 54](https://cloud.githubusercontent.com/assets/8616947/6447429/8b4de064-c112-11e4-8409-579ea472fdb4.png)
![ios simulator screen shot 02 mar 2015 19 26 56](https://cloud.githubusercontent.com/assets/8616947/6447432/94f1444e-c112-11e4-8036-947060f9040b.png)

**Comment by marinotws** [comment]
The problem is status bar ... 

newRect = superView_.bounds;        
newRect.size.height = newRect.size.height - 20; <--- i put a path 

bye

**Comment by 0x0c** [comment]
Thank you!
