### ISSUE TITLE
Player view frame don't set correct

### ISSUE THREAD

**Issue by morteza2128** [0x0c/LMMediaPlayer#26]
When i set frame for player it has issue but when click on full screen and back it will be fix 
![ios simulator screen shot jul 9 2015 11 23 10 pm](https://cloud.githubusercontent.com/assets/3517532/8604043/4c676f34-2691-11e5-8ed8-a5132aabc592.png)
![ios simulator screen shot jul 9 2015 11 23 34 pm](https://cloud.githubusercontent.com/assets/3517532/8604044/4cee8122-2691-11e5-92db-7157e73bd194.png)

**Comment by 0x0c** [comment]
Please tell me how to set the frame.
