### ISSUE TITLE
Could not load NIB  with name 'LMMediaPlayerView' in Swift project

### ISSUE THREAD

**Issue by hanappaula** [0x0c/LMMediaPlayer#31]
I've installed LMMediaPlayer through CocoaPods in a swift project and on a ViewController I wrote this code (following README):

```
override func viewDidLoad() {
        // Do any additional setup after loading the view, typically from a nib.

        var url = NSURL(string: "URL")

        let dict: [NSObject : AnyObject] = [
            LMMediaItemInfoURLKey        : url!,
            LMMediaItemInfoContentTypeKey : (1)
        ]

        player = LMMediaPlayerView.sharedPlayerView()
        item1 = LMMediaItem.init(info:dict)

        player.mediaPlayer.addMedia(item1)
        self.view.addSubview(player)
        player.mediaPlayer.play()

        super.viewDidLoad()
}
```

but the project is crashing with this message:

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/092760CB-F3F0-458A-93AC-5F87506A8340/YTDraggableVideo.app> (loaded)' with name 'LMMediaPlayerView''

I'm having this problem using Xcode 7.3.1 and Deployment Target 9.3.

**Comment by dreampowder** [comment]
I've solved this issue by manually dragging all files into a folder inside the project instead of using cocoapods.

**Comment by 0x0c** [comment]
I think the issue is caused by CocoaPods with Swift.
In Objective-C, there are no problems.

**Comment by 0x0c** [comment]
Please add xib file manually.
